### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by qianqian78** [redkale/redkale-oss#1]
修改cacheable = false，之后才可以登录。

源文件如下：
@Entity(**cacheable = true**)
@Table(name = "sys_usermember", comment = "员工信息表", uniqueConstraints = {
    @UniqueConstraint(name = "unique", columnNames = {"account"})})
public class UserMember extends BaseEntity {

**Comment by redkale** [comment]
Bug已修复， EntityCache使用新版的Copier参数写反了
